output "aws_account_id" {
  description = "AWS account ID used for provisioning resources"
  value = data.aws_caller_identity.current.account_id
}
output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "vpc_id" {
  value = module.vpc.vpc_id
  description = "ID of the associated VPC"
}

output "vpc_cidr_block" {
  value = module.vpc.vpc_cidr_block
  description = "CIDR block of the associated VPC"
}

output "public_subnets" {
  value = module.vpc.public_subnets
  description = "Public Subnets associated to VPC"
}

output "eks_worker_sg" {
  value       = aws_security_group.worker_group_mgmt_one.id
  description = "EKS Workers Security Group"
}

output "public_route_table_ids" {
  value       = module.vpc.public_route_table_ids
  description = "Public Route Table IDs"
}

output "private_route_table_ids" {
  value       = module.vpc.private_route_table_ids
  description = "Public Route Table IDs"
}
