image:
  repository: ${image}
  tag: ${tag}
  pullPolicy: IfNotPresent

replicaCount: 1
clusterName: ${clusterName}

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  name: ${aws_lb_controller_sa}

rbac:
  # Specifies whether rbac resources should be created
  create: true

nodeSelector:
  kubernetes.io/os: linux
